### PR TITLE
Upgrade all dependencies to the latest version and make everything work

### PR DESCRIPTION
**Pull request by lucifer1004**
All dependencies have been upgraded, and all npm scripts have been tested.

### CODE REVIEW

**Review by frenzzy — APPROVED** [review]

**Comment by lucifer1004** [comment]
Seems no auto-merge is configured?

**Comment by lucifer1004** [comment]
Will it be merged?

**Comment by frenzzy** [comment]
Thank you!

**Comment by lucifer1004** [comment]
I am starting on developing a JS library, and this project helped me a lot. It is my honor to contribute to it and make it up-to-date.

**Pull request merged**
